apiVersion: v1
kind: ReplicationController
metadata:
  name: demorc
spec:
  replicas: 3
  selector:
    app: david
  template:
    metadata:
      name: demopod
      labels:
        app: david
spec:
  containers:
  - name: tomcat
    image: antonydavid96/mywar
    ports:
      - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: demoservice
spec:
  type: NodePort
  selector:
    app: david
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30005